#!/usr/bin/env bash
# Switch the active recipe and sync MCP env vars into `.claude/.env`
# so `source .claude/.env && claude` picks up recipe-specific timeouts
# / output caps.
#
# Usage:
#   scripts/set_active_recipe.sh <recipe-name>
#   scripts/set_active_recipe.sh --list
#   scripts/set_active_recipe.sh --current
#   scripts/set_active_recipe.sh --env           # regenerate .claude/.env only
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && (pwd -W 2>/dev/null || pwd))"
cd "$REPO_ROOT"

usage() {
  cat <<'EOF'
Usage: set_active_recipe.sh <recipe-name>
       set_active_recipe.sh --list       # list available recipes
       set_active_recipe.sh --current    # show currently active recipe
       set_active_recipe.sh --env        # regenerate .claude/.env for active recipe
EOF
}

emit_env() {
  local recipe="$1"
  local env_file="$REPO_ROOT/.claude/.env"

  if ! command -v uv >/dev/null 2>&1; then
    echo "[set_active_recipe] WARN uv not found — .claude/.env not regenerated" >&2
    return 0
  fi

  mkdir -p "$REPO_ROOT/.claude"
  uv run python - "$recipe" "$env_file" <<'PY'
import sys, os
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent / ".claude" / "hooks"))
# Fallback: resolve by CWD since stdin heredoc loses __file__ context.
HERE = Path(os.getcwd())
sys.path.insert(0, str(HERE / ".claude" / "hooks"))

from _recipe_config import parse_mcp_block, MCP_DEFAULTS  # type: ignore

recipe = sys.argv[1]
out = Path(sys.argv[2])
cfg = parse_mcp_block(HERE / "recipes" / recipe / "recipe.yaml")
timeout_ms = int(cfg.get("timeout_seconds") or MCP_DEFAULTS["timeout_seconds"]) * 1000
max_out = int(cfg.get("max_tool_output_tokens") or MCP_DEFAULTS["max_tool_output_tokens"])
lines = [
    "# Auto-generated by scripts/set_active_recipe.sh. Source before `claude`:",
    f"#   source .claude/.env && claude",
    f"# Recipe: {recipe}",
    f"export CLAUDE_ACTIVE_RECIPE={recipe}",
    f"export MCP_TIMEOUT={timeout_ms}",
    f"export MAX_MCP_OUTPUT_TOKENS={max_out}",
    # 1h prompt-cache TTL. Claude Code's 2026-03-06 default reverted to 5m,
    # causing 17-26% cost inflation on real workloads (GH #46829, #48082).
    # Critical coupling bug (GH #45381): ANTHROPIC_DISABLE_TELEMETRY=true
    # SILENTLY disables this 1h TTL — do NOT set that env var here.
    "export ENABLE_PROMPT_CACHING_1H=true",
    "",
]
out.write_text("\n".join(lines), encoding="utf-8")
print(f"[set_active_recipe] wrote {out} (MCP_TIMEOUT={timeout_ms}ms, MAX_MCP_OUTPUT_TOKENS={max_out})")
PY
}

case "${1:-}" in
  "" | --help | -h) usage; exit 0 ;;
  --list)
    echo "Available recipes:"
    for d in recipes/*/; do
      name="${d#recipes/}"; name="${name%/}"
      [ "$name" = "_template" ] && continue
      echo "  - $name"
    done
    exit 0
    ;;
  --current)
    if [ -f .claude/last_recipe.txt ]; then
      cat .claude/last_recipe.txt
    else
      echo "(no active recipe — falls back to _template)"
    fi
    exit 0
    ;;
  --env)
    if [ ! -f .claude/last_recipe.txt ]; then
      echo "ERROR: no active recipe (run set_active_recipe.sh <name> first)" >&2
      exit 1
    fi
    recipe="$(tr -d '[:space:]' < .claude/last_recipe.txt)"
    emit_env "$recipe"
    exit 0
    ;;
esac

NAME="$1"

if [ ! -d "recipes/$NAME" ]; then
  echo "ERROR: recipes/$NAME does not exist." >&2
  echo "Create one first: cp -r recipes/_template recipes/$NAME" >&2
  exit 1
fi

echo "$NAME" > .claude/last_recipe.txt
echo "[set_active_recipe] Active recipe: $NAME"

# Rebuild context pack + regenerate env file.
if command -v uv >/dev/null 2>&1; then
  uv run python scripts/make_context_pack.py >/dev/null
  echo "[set_active_recipe] Context pack rebuilt (.claude/CLAUDE.md)"
  emit_env "$NAME"
  echo "[set_active_recipe] Run 'source .claude/.env' before starting claude to apply MCP env."
else
  echo "[set_active_recipe] WARNING: uv not found — context pack and .claude/.env NOT regenerated." >&2
  echo "                    Install uv, then run: scripts/set_active_recipe.sh --env" >&2
fi
